ted_data = {
    'cn':['Foo Bar'],
    'givenName':[],
    'sn':[],
    'inetUserStatus':[],
    'utexasEduPersonEid':['foo001'],
    'utexasEduPersonUin':['1231231231231231'],
    'utexasEduPersonIsoNumber':[],
    'utexasEduPersonOrgUnitName':[],
    'utexasEduPersonPubAffiliation':[],
    'eduPersonAffiliation':[],
    'utexasEduPersonPrimaryTitle':[],
    'utexasEduPersonHighestDegree':[],
    'utexasEduPersonCourseNumber':[],
    'utexasEduPersonOrgUnitName':[],
    'utexasEduPersonMajorDept':[],
    'mail':[],
    'utexasEduPersonEntitlementCode':[],
}
